# Generated by Django 4.0.6 on 2022-07-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_available_alter_book_avg_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avg_rating',
            field=models.FloatField(verbose_name='Average Rating'),
        ),
    ]
