# Generated by Django 4.0.6 on 2022-07-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_avg_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Library Name')),
                ('manager', models.CharField(max_length=50, verbose_name='Manager')),
                ('distance', models.PositiveIntegerField(verbose_name='Distance')),
                ('open', models.BooleanField(default=True, verbose_name='Open')),
            ],
        ),
    ]
